
# This workflow will install Python dependencies, run tests and lint with a multiple versions of Python
name: CloudFormation CLI CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    env:
      AWS_DEFAULT_REGION: us-east-1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip 'attrs==19.2.0' wheel -r requirements.txt
    - name: Install cli
      run: |
        pip install .
    - name: pre-commit, twine checks
      run: |
        pre-commit run --all-files
        python setup.py sdist bdist_wheel
        twine check ./dist/*
    - name: Publish distribution 📦 to Test PyPI (If triggered from release)
      uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_KEY_CLOUDFORMATION_CLI }}
          repository_url: https://test.pypi.org/legacy/
      if: github.event_name = "release"

